-- =============================================================================
-- Vcare.life Database Schema Setup for Supabase
-- Run this script in the Supabase Dashboard -> SQL Editor -> New Query
-- =============================================================================

-- 1. PROFILES TABLE (Stores both Seniors and Caregivers)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    full_name TEXT,
    role TEXT CHECK (role IN ('senior', 'caregiver')),
    phone TEXT,
    date_of_birth DATE,
    gender TEXT,
    preferred_language TEXT DEFAULT 'English',
    emergency_contact_name TEXT,
    emergency_contact_relationship TEXT,
    emergency_contact_phone TEXT,
    onboarding_complete BOOLEAN DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 2. CAREGIVER LINKS TABLE (Connects Caregiver to Senior)
CREATE TABLE IF NOT EXISTS public.caregiver_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caregiver_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    senior_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()),
    UNIQUE (caregiver_id, senior_id)
);

-- 3. MEDICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.medications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    dosage TEXT,
    scheduled_time TEXT,
    taken BOOLEAN DEFAULT FALSE,
    taken_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- 4. CALL LOGS TABLE
CREATE TABLE IF NOT EXISTS public.call_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    senior_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    call_id TEXT,
    status TEXT DEFAULT 'completed',
    transcript TEXT,
    duration INTEGER DEFAULT 0,
    distress_detected BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now())
);

-- =============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- =============================================================================

-- Enable RLS on all tables
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.caregiver_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.call_logs ENABLE ROW LEVEL SECURITY;

-- PROFILES POLICIES
CREATE POLICY "Users can view own profile" 
    ON public.profiles FOR SELECT 
    USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile" 
    ON public.profiles FOR INSERT 
    WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
    ON public.profiles FOR UPDATE 
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

CREATE POLICY "Caregivers can view linked senior profiles" 
    ON public.profiles FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public.caregiver_links 
            WHERE caregiver_links.caregiver_id = auth.uid() 
            AND caregiver_links.senior_id = profiles.id
        )
    );

-- CAREGIVER_LINKS POLICIES
CREATE POLICY "Caregivers can view their own links" 
    ON public.caregiver_links FOR SELECT 
    USING (auth.uid() = caregiver_id);

CREATE POLICY "Caregivers can insert links" 
    ON public.caregiver_links FOR INSERT 
    WITH CHECK (auth.uid() = caregiver_id);

CREATE POLICY "Seniors can view who is linked to them" 
    ON public.caregiver_links FOR SELECT 
    USING (auth.uid() = senior_id);

-- MEDICATIONS POLICIES
CREATE POLICY "Seniors can view own medications" 
    ON public.medications FOR SELECT 
    USING (auth.uid() = senior_id);

CREATE POLICY "Seniors can update own medications" 
    ON public.medications FOR UPDATE 
    USING (auth.uid() = senior_id);

CREATE POLICY "Seniors can delete own medications"
    ON public.medications FOR DELETE
    USING (auth.uid() = senior_id);

CREATE POLICY "Caregivers can view linked senior medications" 
    ON public.medications FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public.caregiver_links 
            WHERE caregiver_links.caregiver_id = auth.uid() 
            AND caregiver_links.senior_id = medications.senior_id
        )
    );

CREATE POLICY "Caregivers can insert medications for linked seniors" 
    ON public.medications FOR INSERT 
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM public.caregiver_links 
            WHERE caregiver_links.caregiver_id = auth.uid() 
            AND caregiver_links.senior_id = medications.senior_id
        )
    );

CREATE POLICY "Caregivers can update medications for linked seniors" 
    ON public.medications FOR UPDATE 
    USING (
        EXISTS (
            SELECT 1 FROM public.caregiver_links 
            WHERE caregiver_links.caregiver_id = auth.uid() 
            AND caregiver_links.senior_id = medications.senior_id
        )
    );

CREATE POLICY "Caregivers can delete medications for linked seniors"
    ON public.medications FOR DELETE
    USING (
        EXISTS (
            SELECT 1 FROM public.caregiver_links
            WHERE caregiver_links.caregiver_id = auth.uid()
            AND caregiver_links.senior_id = medications.senior_id
        )
    );

-- CALL_LOGS POLICIES
CREATE POLICY "Seniors can view own call logs" 
    ON public.call_logs FOR SELECT 
    USING (auth.uid() = senior_id);

CREATE POLICY "Caregivers can view linked senior call logs" 
    ON public.call_logs FOR SELECT 
    USING (
        EXISTS (
            SELECT 1 FROM public.caregiver_links 
            WHERE caregiver_links.caregiver_id = auth.uid() 
            AND caregiver_links.senior_id = call_logs.senior_id
        )
    );

-- =============================================================================
-- REALTIME SUBSCRIPTIONS
-- Enable realtime updates for medications and call logs
-- =============================================================================
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'medications'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.medications;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' AND tablename = 'call_logs'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.call_logs;
    END IF;
END $$;
